In [30]:
import torch
import numpy as np
import pandas as pd

Basic tensor construction

In [17]:
a = torch.tensor([1,2,3,34,4,4,5])
print(a) # shows tensor object
print(a[2]) # same indexing as normal

print(a.dtype) # shows how to find the data type of a tensor
print(a.type(), type(a)) # shows LongTensor which is the same as "long" data type from java and c

# you can create tensors of specific types if you want
b = torch.FloatTensor([1,2,3])
print(b) # note that my ints were converted into floats due to the float tensor method 

# c = torch.FloatTensor(['a', '2', 'd']) # this would get an error since we specified a type. it is like strong typing in c
b = b.type(torch.IntTensor) # this is how you change data types for tensors
print(b) # note that vals are converted back to ints from floats

print(len(b)) # only gets the num of elements in a tensor
print(b.size()) # shows the dimensional sizes (more info basically)
print(b.ndimension()) # shows the number of dimensions 



tensor([ 1,  2,  3, 34,  4,  4,  5])
tensor(3)
torch.int64
torch.LongTensor <class 'torch.Tensor'>
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
3
torch.Size([3])
1


converting dimensions of tensors

In [23]:
a = torch.tensor([1,2,3,4,5])

a_cols = a.view(5,1)
print(a_cols) # as you can see we converted a 1x5 array into a 5x1. using the view method
              #  very odd that the "view" method changes the structure of a data structure but anyways


tensor([[1],
        [2],
        [3],
        [4],
        [5]])


Note for below since numpy_array was used to create torch_tensor and back_to_numpy, changing numpy_array will change the latter two as well. perhaps there is a way to make a copy()?

In [29]:
a_cols_naive = a.view(-1,1) # even if we do not know the dimensions of a we can use -1 and torch will just use max dim
print(a_cols_naive)
print() 
# numpy to torch conversion (this might come up alot or dataframe to tensor conversion)
numpy_array = np.array([1,2,3,4,5,6])
print(numpy_array)
torch_tensor = torch.from_numpy(numpy_array) # convert np array into tensor
print(torch_tensor)
back_to_numpy = torch_tensor.numpy()


tensor([[1],
        [2],
        [3],
        [4],
        [5]])

[1 2 3 4 5 6]
tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)


In [37]:
# converting pandas series to tensor
pandas_series = pd.Series([1,2,3,4,5])
pandas_to_torch = torch.from_numpy(pandas_series.values) # note we needed to use the series values 
print(pandas_series)
print(pandas_to_torch)
# tensor to list conversion
this_tensor = torch.tensor([1,2,3,4])
torch2list = this_tensor.tolist()


0    1
1    2
2    3
3    4
4    5
dtype: int64
tensor([1, 2, 3, 4, 5])


just know that individual values of a tensor are also a tensor