In [30]:
import torch
import numpy as np
import pandas as pd

Basic tensor construction

In [17]:
a = torch.tensor([1,2,3,34,4,4,5])
print(a) # shows tensor object
print(a[2]) # same indexing as normal

print(a.dtype) # shows how to find the data type of a tensor
print(a.type(), type(a)) # shows LongTensor which is the same as "long" data type from java and c

# you can create tensors of specific types if you want
b = torch.FloatTensor([1,2,3])
print(b) # note that my ints were converted into floats due to the float tensor method 

# c = torch.FloatTensor(['a', '2', 'd']) # this would get an error since we specified a type. it is like strong typing in c
b = b.type(torch.IntTensor) # this is how you change data types for tensors
print(b) # note that vals are converted back to ints from floats

print(len(b)) # only gets the num of elements in a tensor
print(b.size()) # shows the dimensional sizes (more info basically)
print(b.ndimension()) # shows the number of dimensions 



tensor([ 1,  2,  3, 34,  4,  4,  5])
tensor(3)
torch.int64
torch.LongTensor <class 'torch.Tensor'>
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
3
torch.Size([3])
1


converting dimensions of tensors

In [23]:
a = torch.tensor([1,2,3,4,5])

a_cols = a.view(5,1)
print(a_cols) # as you can see we converted a 1x5 array into a 5x1. using the view method
              #  very odd that the "view" method changes the structure of a data structure but anyways


tensor([[1],
        [2],
        [3],
        [4],
        [5]])


Note for below since numpy_array was used to create torch_tensor and back_to_numpy, changing numpy_array will change the latter two as well. perhaps there is a way to make a copy()?

In [29]:
a_cols_naive = a.view(-1,1) # even if we do not know the dimensions of a we can use -1 and torch will just use max dim
print(a_cols_naive)
print() 
# numpy to torch conversion (this might come up alot or dataframe to tensor conversion)
numpy_array = np.array([1,2,3,4,5,6])
print(numpy_array)
torch_tensor = torch.from_numpy(numpy_array) # convert np array into tensor
print(torch_tensor)
back_to_numpy = torch_tensor.numpy()


tensor([[1],
        [2],
        [3],
        [4],
        [5]])

[1 2 3 4 5 6]
tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)


In [37]:
# converting pandas series to tensor
pandas_series = pd.Series([1,2,3,4,5])
pandas_to_torch = torch.from_numpy(pandas_series.values) # note we needed to use the series values 
print(pandas_series)
print(pandas_to_torch)
# tensor to list conversion
this_tensor = torch.tensor([1,2,3,4])
torch2list = this_tensor.tolist()


0    1
1    2
2    3
3    4
4    5
dtype: int64
tensor([1, 2, 3, 4, 5])


just know that individual values of a tensor are also a tensor

also know that a tensor is not the same as a python number and thus we sometimes should convert a tensor element into a python number as shown below
- note that the same logic can apply with a list: use .tolist()

In [39]:
tensorTest = torch.tensor([1,2,3,45,5])
tensorElement = tensorTest[0] # this is a tensor el
print(1 + tensorElement) # okay... so note that the result is also a tensor 
tensor2python = tensorElement.item() # converts tensor to py num
print(1 + tensor2python) # note that now the result is just a normal python int

tensor(2)
2


## Indexing and slicing 
- note that slicing is using the same logic as slicing in normal python lists

In [43]:
c = torch.tensor([20,1,2,3,0])
b = c[1:4] # as with normal py left side of colon is 0 indexed, right side is 1 indexed
print(b) # slicing 
c[3:5] = torch.tensor([300.0, 400.0]) # you can change the vals of a slice and affec the og tensor on the fly
print(c) # same logic as py lists really.

tensor([1, 2, 3])
tensor([ 20,   1,   2, 300, 400])


## Vector Addition and Subtraction 

In [54]:
# first lets make the two vectors that we will use u, v 
u = torch.tensor([[1], [0]])
v = torch.tensor([[0], [1]])
print(u)
print(v)
# now let us add them and store them in z
z = u + v
print('========================')
print('u + v =', ' ')
print(z)
# now let us try vector scalar multiplication
y = torch.tensor([[1],[2]])
z = 2*y
print('========================')
print('scalar multiply 2y')
print(z)

tensor([[1],
        [0]])
tensor([[0],
        [1]])
u + v =  
tensor([[1],
        [1]])
scalar multiply 2y
tensor([[2],
        [4]])


element wise multiplication of two tensors/vectors

In [58]:
u = torch.tensor([[1], [2]])
v = torch.tensor([[3], [2]])
print('u = ')
print(u)
print('v = ')
print(v)
z = u * v
print('u * v = ')
print(z)

u = 
tensor([[1],
        [2]])
v = 
tensor([[3],
        [2]])
u * v = 
tensor([[3],
        [4]])


## dot product
- note only works on 1D tensors so the above tensors u and v had to be rewritten as 1D for this to work

In [62]:
u = torch.tensor([1,2])
v = torch.tensor([3, 1]) # note we had to convert the above tensors into 1D for the dot product to work
print('u = ')
print(u)
print('v = ')
print(v)
z = torch.dot(u, v) 
print(z)

u = 
tensor([1, 2])
v = 
tensor([3, 2])
tensor(7)


In [64]:
# "broadcasting" in torch is simple and done as follows
u = torch.tensor([1,2,34,4])
broadcastOne = u + 1 
print(broadcastOne)

tensor([ 2,  3, 35,  5])


## Universal Functions

In [66]:
a = torch.tensor([1,-1,1,-1])
# can calc mean for all elements as follows
a_mean = a.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long