In [2]:
import torch

Basic tensor construction

In [17]:
a = torch.tensor([1,2,3,34,4,4,5])
print(a) # shows tensor object
print(a[2]) # same indexing as normal

print(a.dtype) # shows how to find the data type of a tensor
print(a.type(), type(a)) # shows LongTensor which is the same as "long" data type from java and c

# you can create tensors of specific types if you want
b = torch.FloatTensor([1,2,3])
print(b) # note that my ints were converted into floats due to the float tensor method 

# c = torch.FloatTensor(['a', '2', 'd']) # this would get an error since we specified a type. it is like strong typing in c
b = b.type(torch.IntTensor) # this is how you change data types for tensors
print(b) # note that vals are converted back to ints from floats

print(len(b)) # only gets the num of elements in a tensor
print(b.size()) # shows the dimensional sizes (more info basically)
print(b.ndimension()) # shows the number of dimensions 



tensor([ 1,  2,  3, 34,  4,  4,  5])
tensor(3)
torch.int64
torch.LongTensor <class 'torch.Tensor'>
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
3
torch.Size([3])
1


converting dimensions of tensors

In [23]:
a = torch.tensor([1,2,3,4,5])

a_cols = a.view(5,1)
print(a_cols) # as you can see we converted a 1x5 array into a 5x1. using the view method
              #  very odd that the "view" method changes the structure of a data structure but anyways


tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [24]:
a_cols_naive = a.view(-1,1) # even if we do not know the dimensions of a we can use -1 and torch will just use max dim
print(a_cols_naive)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
